sudo: false
dist: trusty

language: python
python:
  - "3.6"

cache: pip

install:
  - pip install .
  - pip install tox-travis
  - pip install coverage
  - pip install coveralls


script:
  - tox

after_success:
  - coveralls
  - coverage report -m


jobs:
  include:
  - python: 3.6
    env: TOXENV=style
  - python: 3.6
    env: TOXENV=manifest
  - python: 3.6
    env: TOXENV=lint

matrix:
  allow_failures:
    - python: 3.6
      env: TOXENV=lint

deploy:
  provider: pypi
  user: Wooble
  password:
    secure: hCCjmC5IU/Ch5Ux1WpOwnI5/veifCQ4uTs7z6HL7tQaaFkLArGlTSKuAGTs8P753PlxJwTiLvjYRkjHt0Tzav6GoZ3TkU4/QHnd6JZLhOth9uTj7ENgW3kWJ1zwZU9acLqDub1jqXglJVUWk6Ave1UMkNLFfhSnLW+v4x8m94Ww=
  on:
    condition: "! $TOXENV =~ ^flake8|lint|manifest$"
    tags: true
    python: 3.6
  distributions: "sdist bdist_wheel"